{% set name = "python-octaviaclient" %}
{% set version = "3.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-octaviaclient-{{ version }}.tar.gz
  sha256: c2b621098de0a9c92548af256a9b2016adb9622ddac041a06ab5b66bb5b590ee

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pbr >=2.0.0
    - pip
    - python >=3.8
    - setuptools
  run:
    - cliff !=2.9.0,>=2.8.0
    - keystoneauth1 >=3.18.0
    - osc-lib >=1.14.1
    - oslo.serialization !=2.19.1,>=2.18.0
    - oslo.utils >=3.33.0
    - pbr !=2.1.0,>=2.0.0
    - python >=3.8
    - python-neutronclient >=6.7.0
    - python-openstackclient >=3.12.0
    - requests >=2.14.2

test:
  imports:
    - octaviaclient
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://docs.openstack.org/python-octaviaclient/latest/
  summary: Octavia client for OpenStack Load Balancing
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tschoonj
